### PR TITLE
#514 Integration of https://github.com/Nodeclipse/GradleEditor

### PR DESCRIPTION
**Pull request by cmoine**
Signed-off-by: Christophe Moine <christophe.moine@free.fr>

### CODE REVIEW

**Comment by donat** [comment]
Hi, @cmoine! Sorry for the late reply, I was away for a few weeks. From now on I'll get back to you much faster.

One thing we discussed internally is that the same editor support can be achieved with Eclipse's [generic editor](https://www.eclipse.org/eclipse/news/4.7/M3/#generic-editor). That way Buildship wouldn't have to define yet another editor for Gradle files. The only problem is that the generic editor is available since Eclipse 4.7, so older Eclipse releases still wouldn't have any syntax highlighting. That being said, I still think your PR is valuable, I just wanted to point out the possibility.

**Comment by donat** [comment]
In the meanwhile, I've contacted the Eclipse IP team to verify if we are allowed to merge this PR. Most probably we are, but I'd like to be 100% sure.

**Comment by cmoine** [comment]
Wahou, Generic Editor feature looks amazing !!! :O And funny thing, the example is a Gradle editor !!!!! :D

> The only problem is that the generic editor is available since Eclipse 4.7
But my PR is on master, hence for Eclipse 4.7, isn't it ? Did you plan to merge my PR in older branches ?

I already tried to contact someone, but I don't remember who, I cannot find the message again :( (did I dream ? :) )

To be honest I would prefer the Generic Editor for the following reasons:
- We go with something fresh, and modern (I hope !) :)
- We won't have any licensing issues (even if you have confirmation, we never know what can do some other people...)
- We may bring an added value compared to the STS plugin editor: it is not just copy/paste.
- That would make it more homogeneous to provide a Gradle editor just like eclipse suggest to do it in the News  & NoteWorthy
- That is interesting from my point of view ;) (more than copy/pasting code :) )

What do you think ?

**Comment by donat** [comment]
I'd also prefer an implementation with the generic editor, it's only up to you if you want to invest time into the implementation. And thumbs-up for the enthusiasm :)

Feel free to contact us if you need any help with the existing codebase. Also, in case you haven't found it, here's the [Buildship development documentation](https://github.com/eclipse/buildship/blob/master/docs/development/Setup.md).

**Pull request closed without merging**
