### PR TITLE
upgrade spock to 2.3 and groovy to 3.0.19

### PR DESCRIPTION
**Pull request by reinsch82**

### CODE REVIEW

**Review by donat — APPROVED** [review]

**Comment by akurtakov** [comment]
Did all these changes been ip approved by e.g. https://github.com/eclipse/dash-licenses/ ? I'm trying to move Jdt.ls to latest buildship and face a license issue https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2974 .

**Comment by donat** [comment]
Groovy and Spock are test-only dependencies and they should not appear anywhere in production.

**Comment by akurtakov** [comment]
My bad I wanted to ask for org.gradle.toolingapi. No idea why I actually asked at this PR.

**Comment by donat** [comment]
Regarding the org.gradle.toolingapi: years ago the Eclipse IP team allowed us to update the tapi versions without an explicit license review.

**Comment by akurtakov** [comment]
> Regarding the org.gradle.toolingapi dependency: years ago the Eclipse IP team allowed us to update the tapi versions without an explicit license review.

@waynebeaton Can this permission be somehow handled in the dash tool database or the tool itself so buildship downstreams can rely on dash licensetool?

**Comment by waynebeaton** [comment]
@donat where do I find downloads (especially of source) of `org.gradle:gradle-tooling-api:*`. 

I'm looking specifically for some kind of archive format, not a pointer to the source tree  in a Git repository (I can make the latter work, but an archive file is better for a couple of reasons). Scanning these should be easy enough, so I'd like to set us up for future success (other projects have asked for this dependency).

In the meantime... I grabbed the ZIP of the source from the Eclipse Buildship project; we'll use that to push through the review of this version.

**Comment by donat** [comment]
The source jar is available here: [gradle-tooling-api-8.1.1-sources.jar](https://repo.gradle.org/artifactory/libs-releases/org/gradle/gradle-tooling-api/8.1.1/gradle-tooling-api-8.1.1-sources.jar)

**Comment by waynebeaton** [comment]
Thanks. In the future, the IPLab scanner will look on repo.gradle.org for source for this and other `org.gradle` packages.

**Pull request merged**
