### PR TITLE
Bug 472223 - Show a warning in case the project root location is inside

### PR DESCRIPTION
**Pull request by donat**
the workspace

Change-Id: Id84690c3368ce170a9c19f903055ea659b37b9b6
Signed-off-by: Simon Scholz <simon.scholz@vogella.com>

Bug 472223 - Show a warning that the root location inside the workspace
will be changed

Change-Id: I4070d25898701ae432e5420dcc01554c60806d67
Signed-off-by: Simon Scholz <simon.scholz@vogella.com>

Bug 472223 - Rename root folder in workspace if necessary

Change-Id: Ia0dc9c39ed102f2f273075d1a4b4af4d24c66798
Signed-off-by: Simon Scholz <simon.scholz@vogella.com>

Bug 472223 - Added spock integration test for Bug 472223

Change-Id: Iaec9be5d83b5820ddbe43485a5edef849e613fc8
Signed-off-by: Simon Scholz <simon.scholz@vogella.com>

Bug 472223 - Externalized warning and removed whitespace

Change-Id: If17d65f370827af2214e2daa5f70c81cd75fad8d
Signed-off-by: Simon Scholz <simon.scholz@vogella.com>

Add settings to Oomph model to ignore warnings on the unused @SuppressWarnings arguments

Signed-off-by: Donat Csikos <csdonat@gmail.com>

Bug 473389 - NPEs during UI integration tests in the UIPlugin Activator

Change-Id: Ic35a73404b11b9ebb8a8e551fc4f0f285bbbb9d4
Signed-off-by: Simon Scholz <simon.scholz@vogella.com>

Review

Bug 470071 - Includes and excludes are not applied to source folders

Signed-off-by: Ian Stewart-Binks <istewart@redhat.com>

Bug 470071: Make code more compact, clean up.

Signed-off-by: Ian Stewart-Binks <istewart@redhat.com>

Minor code formatting

Signed-off-by: Donat Csikos <csdonat@gmail.com>

Format and organize imports in class ProjectImportJob

Signed-off-by: Donat Csikos <csdonat@gmail.com>

Replace FixedRequestAttributes field with method argument

Signed-off-by: Donat Csikos <csdonat@gmail.com>

Move things around a little

Signed-off-by: Donat Csikos <csdonat@gmail.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=472223

**Comment by donat** [comment]
This PR is a reviewed version of #135 
I took the original PR, added some changes and squashed them into one and rebased to the latest master.

**Comment by etiennestuder** [comment]
I don't think renaming the folder is the right thing to do. If I try to import a project and the folder gets renamed by the tool, I'd not be happy as a user. Let's first understand where the root cause of the problem is in Buildship, then think of the best solution for the user, then think of how to implement it in Buildhship.

**Comment by etiennestuder** [comment]
Replaced by PR #148 that avoids any folder renaming.

**Pull request closed without merging**
