### PR TITLE
Basic editor support for build scripts

### PR DESCRIPTION
**Pull request by cmoine**
Follows up https://github.com/eclipse/buildship/pull/564

### CODE REVIEW

**Comment by cmoine** [comment]
Hi Donat, 

Thank you very much for your careful testing. That is strange that tab doesn't work.

I think (hope) it shouldn't be too complicated.

I will rest the weekend first :)

Cheers.


----- Original Message -----

**Comment by donat** [comment]
Sorry, if my previous message sounded a bit pushy. Take your time and let us know if we can help.

**Comment by cmoine** [comment]
Ah, no, I didn't take it that way, no pb :)

The method TextSourceViewerConfiguration.getTabWidth was returning zero because of wrong PreferenceStore :) Don't hesitate if you find other problems.

Cheers.

**Comment by cmoine** [comment]
I also changed the @author into Contributor into the header comment, because I saw it was like that in other files :)

**Comment by donat** [comment]
About the license header: What you found is the old header. If you have a look at the newer source files (like [this](https://github.com/eclipse/buildship/blob/f404ed1ce72823a998f73586545b5b0e4d0fac18/org.eclipse.buildship.core/src/main/java/org/eclipse/buildship/core/preferences/ModelPersistence.java)) then you'll find the proper header.

**Comment by cmoine** [comment]
I think it is because of my mistake when I did a merge with an old branch. I forced a push: I hope it will be much better.

**Comment by cmoine** [comment]
Great ! Ouch, I forgot to replace to @author back. Do you want me to do it ?

**Comment by donat** [comment]
Yes, it would be better if you do it :)

**Comment by cmoine** [comment]
It would be a shame to give up at this point :) Done !

**Pull request merged**
