### PR TITLE
Restore lib/ folder for core.tests and oomph.test

### PR DESCRIPTION
**Pull request by fvclaus**
@donat , I looked into `BundlePlugin` as you pointed out in https://github.com/eclipse/buildship/pull/1154#issuecomment-1121091278

I did not want to complicate the `BundlePlugin` implementation by making it aware of the shared test dependencies. Which would require reading dependencies between projects and figuring out what is shared. Instead, I took a second look at the duplicate classpath issue of https://github.com/eclipse/buildship/pull/1154 and came up with a better solution: I made the `oomph.test` dependency a fragment host of `oomph` not of `core`.

### CODE REVIEW

**Comment by donat** [comment]
So we had the duplicate classpath issue only because of `oomph.test` and `core.test` specified the same fragment host? That makes sense.

**Comment by donat** [comment]
I've tested it locally and looks good. Are you planning to update the lib folder in `ui.test`?

**Comment by fvclaus** [comment]
> So we had the duplicate classpath issue only because of `oomph.test` and `core.test` specified the same fragment host? That makes sense.

Exactly. When I provided the first fix, I thought thats the way its supposed to be. This is way I made up the "testdependencies" project.

> Are you planning to update the lib folder in ui.test?
Done. The `bundled` dependency for Spock was missing in `build.gradle`

**Comment by donat** [comment]
Thank you @fvclaus!

**Pull request merged**
