### PR TITLE
Allow Java Platform to be first in classpath

### PR DESCRIPTION
**Pull request by jsarman**
Change order of classpath building to allow java platform to load before external dependencies.

### CODE REVIEW

**Comment by donat** [comment]
First of all thank you for contribution! The change looks simple. But before we merge it would you mind giving us some context why is this change needed, perhaps with a sample project exhibiting the problem?
Also, please note that the ip-validation has failed for your project, probably due to a missing [signed-off-by entry in the commit message](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#via_GitHub).

**Comment by donat** [comment]
Ah, I just found [Bug 495328](https://bugs.eclipse.org/bugs/show_bug.cgi?id=495328). I suppose that is related to this pull request.

**Comment by jsarman** [comment]
Yeah I worked with Aaron to verify and create  Bug 495328.  I was able to setup buildship and debug it to the simple code order change.  I made the change with the github built in editor and I guess by doing it that way  github does not sign the code.  I can go through all the steps to ensure its signed off if needed.

**Comment by oehme** [comment]
I think sign-off needs to be the last statement in a commit message.

Also, please include an integration test that demonstrates this change works as expected.

**Comment by oehme** [comment]
Thank you for the fix! I will backport it to 1.0.16 too.

**Pull request merged**
