### PR TITLE
Update Guava version and dependency infrastructure

### PR DESCRIPTION
**Pull request by donat**

### CODE REVIEW

**Comment by donat** [comment]
CI build [passed](https://builds.gradle.org/buildConfiguration/Tooling_Buildship_Checkpoint_Full_Test_Coverage_Fork_Phase_33/76620015?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true); merging.

**Comment by merks** [comment]
Thank you for working on this issue!!  ❤️ 

There are currently only two contributions pulling in the older guava version:

image

It would be truly awesome if Buildship would contribute an update with the changes in the PR to SimRel for M1!  The lsp4j work in also planned for today:

https://github.com/eclipse-lsp4j/lsp4j/pull/782#issuecomment-1884903256

**Comment by merks** [comment]
We're down to just this dependency:

image

I tried testing locally with https://download.eclipse.org/buildship/updates/latest-snapshot to see if that has the changes, but alas it does not...

**Comment by donat** [comment]
Thanks for directly reaching out to me. I've kicked off a snapshot release manually. I'll look into creating a patch release later this week.

**Comment by merks** [comment]
I hope you don't mind that I contributed your snapshot to SimRel.  I really wanted the old version of Guava gone and some additional early testing of your release before you release it seems like a good thing...

**Comment by donat** [comment]
No, not at all, thanks for doing that! I'll make sure to contribute a final Buildship release for the upcoming simrel.

**Comment by donat** [comment]
@merks I've created a final release and going to add it to simrel: https://github.com/eclipse-simrel/simrel.build/pull/189

**Pull request merged**
